from enum import Enum


class CommonLanguage(str, Enum):
    PROCESSING_MESSAGE = "PROCESSING_MSG"
    TRANSLATING_MESSAGE = "TRANSLATE_MSG"
    GENERATING_IMAGE = "GENERATING_IMAGE"
    GENERATING_VIDEO = "GENERATING_VIDEO"
    GENERATING_RESPONSE = "GENERATING_RESPONSE"
    RETRIEVING_DOCUMENTS = "RETRIEVING_DOCUMENTS"
    FINDING_LAWYER = "FINDING_LAWYER"
    INTENT_DETECTION = "INTENT_DETECTION"
    GENERATING_RESPONSE_DENIAL = "GENERATING_RESPONSE_DENIAL"
    GENERATING_RESPONSE_MODIFY = "GENERATING_RESPONSE_MODIFY"
